title: 
theme: jekyll-theme-minimal
# description: [A short description of your site's purpose]
logo: assets/icon-256x256.png
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
